import { readFile } from "node:fs/promises";
import { describe, expect, it } from "@effect/vitest";
import { Result, Schema } from "effect";
import { validatePluginSource, preparePluginPackage } from "./authoring-validation.js";
import { canonicalPluginJson, digestPluginBytes } from "./plugin-contract.js";
import { inspectPluginArchive } from "./plugin-archive.js";
import {
  buildDeterministicPluginArchive,
  PackageManifest,
  parsePackagedPluginArchive,
} from "./package-archive.js";

const githubPackageFiles = async (): Promise<Readonly<Record<string, Uint8Array>>> => {
  const packagePaths = [
    ["plugin.json", "plugins/github/package-manifest.json"],
    ["catalog.json", "plugins/github/catalog.json"],
    ["config.json", "plugins/github/config.json"],
    ["provenance.json", "plugins/github/provenance.json"],
    ["dist/server.mjs", "plugins/github/source/server.mjs"],
    ["LICENSE", "plugins/github/LICENSE"],
    ["NOTICE", "plugins/github/NOTICE"],
  ] as const;
  const entries = await Promise.all(
    packagePaths.map(
      async ([destination, source]) =>
        [destination, new Uint8Array(await readFile(source))] as const,
    ),
  );
  return Object.fromEntries(entries);
};

const loadGolden = async (): Promise<{
  readonly artifactDigest: string;
  readonly manifestDigest: string;
  readonly catalogDigest: string;
  readonly configDigest: string;
  readonly byteLength: number;
  readonly entryOrder: ReadonlyArray<string>;
}> => JSON.parse(await readFile("fixtures/golden/offline-package.json", "utf8"));

describe("Phase 1 package archive parity", () => {
  it("produces identical bytes twice and matches golden contract digests", async () => {
    const expectedGolden = await loadGolden();
    const sourceResult = await validatePluginSource("plugins/offline-fixture");
    expect(Result.isSuccess(sourceResult)).toBe(true);
    if (Result.isFailure(sourceResult)) return;
    const input = {
      source: sourceResult.success,
      marketplaceId: "supernala-public",
      versionId: "offline-fixture-1.0.0",
      publishedAt: 0,
    };
    const first = await preparePluginPackage(input);
    const second = await preparePluginPackage(input);
    expect(Result.isSuccess(first)).toBe(true);
    expect(Result.isSuccess(second)).toBe(true);
    if (Result.isFailure(first) || Result.isFailure(second)) return;
    expect(first.success.archiveBytes).toEqual(second.success.archiveBytes);
    expect(first.success.artifactDigest).toBe(expectedGolden.artifactDigest);
    expect(first.success.parsed.version.catalog.digest).toBe(expectedGolden.catalogDigest);
    expect(first.success.parsed.configDigest).toBe(expectedGolden.configDigest);
    expect(first.success.parsed.version.runtime).toMatchObject({
      kind: "managed-package",
      manifestDigest: expectedGolden.manifestDigest,
      entrypoint: "dist/server.mjs",
      node: "22.x",
    });
    expect(first.success.archiveBytes.byteLength).toBe(expectedGolden.byteLength);
    expect(first.success.parsed.entries.map((entry) => entry.path)).toEqual(
      expectedGolden.entryOrder,
    );
  });

  it("parses generated bytes against checked golden Phase 1 version metadata", async () => {
    const expectedGolden = await loadGolden();
    const sourceResult = await validatePluginSource("plugins/offline-fixture");
    expect(Result.isSuccess(sourceResult)).toBe(true);
    if (Result.isFailure(sourceResult)) return;
    const prepared = await preparePluginPackage({
      source: sourceResult.success,
      marketplaceId: "supernala-public",
      versionId: "offline-fixture-1.0.0",
      publishedAt: 0,
    });
    expect(Result.isSuccess(prepared)).toBe(true);
    if (Result.isFailure(prepared)) return;
    const bytes = prepared.success.archiveBytes;
    const parsed = await parsePackagedPluginArchive({
      archiveBytes: bytes,
      marketplaceId: "supernala-public",
      versionId: "offline-fixture-1.0.0",
      publishedAt: 0,
    });
    expect(Result.isSuccess(parsed)).toBe(true);
    if (Result.isFailure(parsed)) return;
    expect(await digestPluginBytes(bytes)).toBe(expectedGolden.artifactDigest);
    expect(canonicalPluginJson(parsed.success.version)).toContain(
      '"publisherNamespace":"supernala"',
    );
    expect(parsed.success.version).toMatchObject({
      id: "offline-fixture-1.0.0",
      marketplaceId: "supernala-public",
      pluginSlug: "offline-fixture",
      version: "1.0.0",
      license: "LicenseRef-Testing-Only",
      status: "published",
      publishedAt: 0,
    });
  });

  it("rejects traversal, links, collisions, bombs, and missing entrypoints", () => {
    const limits = {
      maximumFiles: 2,
      maximumExpandedBytes: 100,
      maximumFileBytes: 80,
      maximumCompressionRatio: 10,
    };
    const cases = [
      { path: "../server.mjs", kind: "file", compressedBytes: 1, expandedBytes: 1 },
      { path: "server.mjs", kind: "symlink", compressedBytes: 1, expandedBytes: 1 },
      { path: "server.mjs", kind: "file", compressedBytes: 0, expandedBytes: 1 },
      { path: "server.mjs", kind: "file", compressedBytes: 1, expandedBytes: 81 },
    ] as const;
    for (const entry of cases) {
      const result = inspectPluginArchive({ entries: [entry], entrypoint: "server.mjs", limits });
      expect(Result.isFailure(result)).toBe(true);
    }
    const collision = inspectPluginArchive({
      entries: [
        { path: "Server.mjs", kind: "file", compressedBytes: 1, expandedBytes: 1 },
        { path: "server.mjs", kind: "file", compressedBytes: 1, expandedBytes: 1 },
      ],
      entrypoint: "server.mjs",
      limits,
    });
    expect(Result.isFailure(collision)).toBe(true);
  });

  it("accepts exact GitHub auth and MIT evidence while rejecting stripped or excess metadata", async () => {
    const files = await githubPackageFiles();
    const parse = (packageFiles: Readonly<Record<string, Uint8Array>>) =>
      parsePackagedPluginArchive({
        archiveBytes: buildDeterministicPluginArchive(packageFiles),
        marketplaceId: "supernala-public",
        versionId: "supernala-public:supernala:github@0.1.0",
        publishedAt: 1,
      });
    const accepted = await parse(files);
    expect(accepted).toMatchObject({
      _tag: "Success",
      success: {
        authentication: {
          kind: "github-app",
          providerRegistration: "supernala-github-app-v1",
          credentialDelivery: "short-lived-installation-token-only",
        },
      },
    });

    const manifest = Schema.decodeUnknownSync(Schema.JsonObject)(
      JSON.parse(new TextDecoder().decode(files["plugin.json"])),
    );
    const { licenseEvidence: _licenseEvidence, ...withoutEvidence } = manifest;
    expect(
      await parse({
        ...files,
        "plugin.json": new TextEncoder().encode(JSON.stringify(withoutEvidence)),
      }),
    ).toEqual(Result.fail("required-evidence-missing"));
    expect(await parse({ ...files, LICENSE: new TextEncoder().encode("MIT\n") })).toEqual(
      Result.fail("invalid-license-evidence"),
    );

    const authentication = Schema.decodeUnknownSync(Schema.JsonObject)(manifest.authentication);
    expect(
      await parse({
        ...files,
        "plugin.json": new TextEncoder().encode(
          JSON.stringify({
            ...manifest,
            authentication: { ...authentication, unreviewedCredential: "forbidden" },
          }),
        ),
      }),
    ).toEqual(Result.fail("invalid-plugin.json"));

    const typedManifest = Schema.decodeUnknownSync(PackageManifest, {
      onExcessProperty: "error",
    })(manifest);
    if (typedManifest.licenseEvidence === undefined)
      throw new Error("test-license-evidence-missing");
    const mismatchedNotice = new TextEncoder().encode(
      "Copyright (c) 2026 Different synthetic holder\n",
    );
    const noticeManifest = PackageManifest.make({
      ...typedManifest,
      licenseEvidence: {
        ...typedManifest.licenseEvidence,
        notice: { path: "NOTICE", sha256: await digestPluginBytes(mismatchedNotice) },
      },
    });
    expect(
      await parse({
        ...files,
        NOTICE: mismatchedNotice,
        "plugin.json": new TextEncoder().encode(JSON.stringify(noticeManifest)),
      }),
    ).toEqual(Result.fail("invalid-license-evidence"));
  });
});
